version: "3.7"

services:
  web:
    image: nginx:1.17
    ports:
      - "1212:80"
    volumes:
      - ./:/var/www
      - ./config/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    restart: unless-stopped
    networks:
      - php-playground

  php:
    build:
      context: .
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php-playground
  composer:
    image: composer
    restart: 'no'
    command: 'install'
    volumes:
    - ./:/app
networks:
  php-playground:
    driver: bridge